name: Verify Installation Script

on:
  push:
    branches: main
  pull_request:
  repository_dispatch:
    types:
      - release-created

jobs:
  verify:
    name:  Install in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get recent tag
        run: echo "LATEST_GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Install CLI
        # manually sending version to avoid ratelimiting errors within actions
        run: bash install.sh ${{ env.LATEST_GIT_TAG }}
        env:
          TERM: xterm

      - name: Check if cli is installed
        run: |
          if ! command -v ops > /dev/null 2>&1; then
            echo "LocalOps cli not found"
            exit 1
          else
            echo "LocalOps cli is installed"
          fi

      - name: Get LocalOps CLI version
        run: echo "LOCALOPS_CLI_VERSION=$(ops version)" >> $GITHUB_ENV

      - name: Print Env
        run: |
          echo "Latest git tag: $LATEST_GIT_TAG"
          echo "Installed LocalOps CLI version: $LOCALOPS_CLI_VERSION"

      - name: Verify CLI version with latest git tag
        run: |
          if [ "${LATEST_GIT_TAG#v}" != "$LOCALOPS_CLI_VERSION" ]; then
            echo "Installed incorrect cli version"
            exit 1
          fi
