name: Verify Installation Script

on:
  push:
    branches: main
  pull_request:

jobs:
  verify:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install CLI
        run: sh install.sh
        env:
          TERM: xterm

      - name: Check if cli is installed
        run: |
          if ! command -v lops > /dev/null 2>&1; then
            echo "LocalOps cli not found"
            exit 1
          else
            echo "LocalOps cli is installed"
          fi

      - name: Get recent tag
        run: echo "LATEST_GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: Verify Version
        run: echo "LOCALOPS_CLI_VERSION=`echo $(lops version)`" >> $GITHUB_ENV

      - name: Print Env
        run: |
          echo $LATEST_GIT_TAG
          echo $LOCALOPS_CLI_VERSION

      - name: Verify CLI version with latest
        run: |
          if [ "${LATEST_GIT_TAG#v}" != "$LOCALOPS_CLI_VERSION" ]; then
            echo "Installed incorrect cli version"
            exit 1
          fi
